#https://localhost:7125/api/WeatherForecast
https://localhost:5001/api/WeatherForecast
#https://localhost:7064/WeatherForecast
#https://localhost:3000/api/WeatherForecast
Accept: application/json

###

POST https://localhost:7125/api/person
Content-Type: application/json

{
  "Name": "Jerry",
  "Reputation": 3
}


###
POST https://localhost:7125/api/entries
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "entries",
    "attributes": {
      "name": "Вася Пупкин",
      "reputation": 8,
      "description": ""
    }
  }
}

###

#GET https://localhost:7125/api/persons?page[size]=30&page[number]=1
#https://localhost:7125/api/persons?page[number]=1&page[size]=10
#GET https://localhost:7125/api/persons?page[offset]=0&page[limit]=50
#https://localhost:7125/api/persons?page[offset]=0&size=50
# НЕ ВЕРНО https://localhost:7125/api/persons?page[offset]=0&page[limit]=30
#ВЕРНо 
GET https://localhost:7125/api/persons?page[size]=30&page[number]=1
Accept: application/vnd.api+json
###
