POST https://localhost:7125/api/notes
Content-Type: application/json

{
  "title": "Описание #2",
  "description": "Bla bla",
  "entryId": "f4065ec1-51f4-4f70-8e09-15e538541e58"
}

###
PATCH https://localhost:7125/api/notes/55422c37-86f5-48f2-84e4-2016146fa688
Content-Type: application/json

{
  "Title": "Super title"
}

###