//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relaks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Entity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Relaks.src.Resources.Entity", typeof(Entity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединения.
        /// </summary>
        internal static string BaseEntries {
            get {
                return ResourceManager.GetString("BaseEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединение.
        /// </summary>
        internal static string BaseEntry {
            get {
                return ResourceManager.GetString("BaseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        internal static string ECompany {
            get {
                return ResourceManager.GetString("ECompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ликвидация.
        /// </summary>
        internal static string ECompany_EndAt {
            get {
                return ResourceManager.GetString("ECompany_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        internal static string ECompany_Name {
            get {
                return ResourceManager.GetString("ECompany_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string ECompany_StartAt {
            get {
                return ResourceManager.GetString("ECompany_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string EiDate {
            get {
                return ResourceManager.GetString("EiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EiEmail {
            get {
                return ResourceManager.GetString("EiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string EiPhone {
            get {
                return ResourceManager.GetString("EiPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        internal static string EiUrl {
            get {
                return ResourceManager.GetString("EiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Встреча.
        /// </summary>
        internal static string EMeet {
            get {
                return ResourceManager.GetString("EMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание встречи.
        /// </summary>
        internal static string EMeet_EndAt {
            get {
                return ResourceManager.GetString("EMeet_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название встречи.
        /// </summary>
        internal static string EMeet_Name {
            get {
                return ResourceManager.GetString("EMeet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало встречи.
        /// </summary>
        internal static string EMeet_StartAt {
            get {
                return ResourceManager.GetString("EMeet_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек.
        /// </summary>
        internal static string EPerson {
            get {
                return ResourceManager.GetString("EPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата смерти.
        /// </summary>
        internal static string EPerson_EndAt {
            get {
                return ResourceManager.GetString("EPerson_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        internal static string EPerson_Name {
            get {
                return ResourceManager.GetString("EPerson_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string EPerson_StartAt {
            get {
                return ResourceManager.GetString("EPerson_StartAt", resourceCulture);
            }
        }
    }
}
