DELETE http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/entry-infos/07315DD9-8587-4B73-A53A-0C399968647E
Accept: application/json
Content-Type: application/json
###

PUT http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/entry-infos/07315DD9-8587-4B73-A53A-0C399968647E
Accept: application/json
Content-Type: application/json

{
  "note": "2022-03-17T12:11:35.798Z",
  "title": "New date about",
  "deletedReason": "",
  "phoneNumber": "8 812 123-45-67",
  "phoneRegion": "ru"
}

###

// SINGLE
GET http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/entry-infos/07315DD9-8587-4B73-A53A-0C399968647E
Accept: application/json
Content-Type: application/json

###
// ALL
GET http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/entry-infos?type=phone
Accept: application/json
Content-Type: application/json

{
  "type": "Phone"
}

###
// CREATE
POST http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/entry-infos
Accept: application/json
Content-Type: application/json

{
  "type": "phone",
  "data": {
    "number": "8 812 123-45-67",
    "region": "ru"
  },
  "Title": "M",
  "deletedReason": "asd"
}

###