DELETE https://localhost:7125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/urls/07C18674-296E-41BE-9087-E92675007059
Accept: application/json
Content-Type: application/json
###

PUT https://localhost:7125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/urls/07C18674-296E-41BE-9087-E92675007059
Accept: application/json
Content-Type: application/json

{
  "note": "2022-03-17T12:11:35.798Z",
  "title": "New date about",
  "deletedReason": "",
  "url": "https://example.com"
}

###

// SINGLE
GET https://localhost:7125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/urls/07C18674-296E-41BE-9087-E92675007059
Accept: application/json
Content-Type: application/json

###
// ALL
GET https://localhost:7125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/urls
Accept: application/json
Content-Type: application/json

###
// CREATE
POST https://localhost:7125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/urls
Accept: application/json
Content-Type: application/json

{
  "url": "https://example.com",
  "Title": "M",
  "deletedReason": ""
}

###