DELETE http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/texts/1C9C78A7-07E7-441D-A09D-551EE68E2616
Accept: application/json
Content-Type: application/json
###

PUT http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/texts/1C9C78A7-07E7-441D-A09D-551EE68E2616
Accept: application/json
Content-Type: application/json

{
  "val": "2acco@mail.ru asd",
  "textType": "email",
  "About": "Another best email",
  "actualStartAt": "2022-03-17T12:11:35.798Z",
  "ActualEndAtReason": "Update about",
  "ActualStartAtReason": ""
}

###

// SINGLE
GET http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/texts/1C9C78A7-07E7-441D-A09D-551EE68E2616
Accept: application/json
Content-Type: application/json

###
// ALL
GET http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/texts?textType=email
Accept: application/json
Content-Type: application/json

###
// CREATE
POST http://localhost:5125/api/entries/01FBDDDD-1D69-4757-A8D2-5050A1AED4D4/texts
Accept: application/json
Content-Type: application/json

{
  "val": "asd@mail.ru",
  "textType": "email",
  "About": "My custom date",
  "actualStartAt": "2022-03-17T12:11:35.798Z",
  "ActualEndAtReason": "",
  "ActualStartAtReason": ""
}
###