// Collection
GET http://localhost:5125/api/entries/01b137da-a3cf-4c08-ac3e-752b3f156ed4/structures/da646b60-bb1e-4a26-8ff9-2c5d4bb7dc14
Accept: application/json
Content-Type: application/json

###

// Delete
DELETE http://localhost:5125/api/entries/01b137da-a3cf-4c08-ac3e-752b3f156ed4/structures/da646b60-bb1e-4a26-8ff9-2c5d4bb7dc14
Accept: application/json
Content-Type: application/json

###

// Create
POST http://localhost:5125/api/entries/01b137da-a3cf-4c08-ac3e-752b3f156ed4/structures
Accept: application/json
Content-Type: application/json

{
  "Title": "Менеджеры",
  "description": "",
  "deletedReason": "",
  "startAt": "2022-03-17T12:11:35.798Z" 
}

###

// Update
PUT http://localhost:5125/api/entries/01b137da-a3cf-4c08-ac3e-752b3f156ed4/structures/da646b60-bb1e-4a26-8ff9-2c5d4bb7dc14
Accept: application/json
Content-Type: application/json

{
"Title": "Abc",
"description": "",
"deletedReason": "",
"startAt": "2022-03-17T12:11:35.798Z"
}